[package]
name = "catalogue"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-cors = "0.6.4"
actix-web = "4.4.0"
async-graphql = "6.0.6"
async-graphql-actix-web = "6.0.6"
bson = { version = "2.7.0", features = ["chrono-0_4"] }
chrono = "0.4.38"
dotenv = "0.15.0"
env_logger = "0.10.0"
fancy-regex = "0.13.0"
hmac = "0.12.1"
jwt = "0.16.0"
lazy_static = "1.4.0"
log = "0.4.20"
mongodb = "2.6.1"
serde = { version = "1.0.188", features = ["derive"] }
serde_json = "1.0.107"
serde_repr = "0.1.17"
sha2 = "0.10.8"
